// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW4Q4TOsaI5Mmq-jIIIjJFc8DETZIHyiI',
    appId: '1:768765672792:web:dcdbdd7fcf51544169392d',
    messagingSenderId: '768765672792',
    projectId: 'task-management-d24b8',
    authDomain: 'task-management-d24b8.firebaseapp.com',
    storageBucket: 'task-management-d24b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccexTLauWpwELwXXfVGBBzFOM1UcyOrU',
    appId: '1:768765672792:android:46c37c591e5b8dd469392d',
    messagingSenderId: '768765672792',
    projectId: 'task-management-d24b8',
    storageBucket: 'task-management-d24b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_urH1RMHPo8MxYadpMSokXJ1Rih4mNz0',
    appId: '1:768765672792:ios:8acee005b87eab7a69392d',
    messagingSenderId: '768765672792',
    projectId: 'task-management-d24b8',
    storageBucket: 'task-management-d24b8.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_urH1RMHPo8MxYadpMSokXJ1Rih4mNz0',
    appId: '1:768765672792:ios:8acee005b87eab7a69392d',
    messagingSenderId: '768765672792',
    projectId: 'task-management-d24b8',
    storageBucket: 'task-management-d24b8.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW4Q4TOsaI5Mmq-jIIIjJFc8DETZIHyiI',
    appId: '1:768765672792:web:91ca08023da96ab469392d',
    messagingSenderId: '768765672792',
    projectId: 'task-management-d24b8',
    authDomain: 'task-management-d24b8.firebaseapp.com',
    storageBucket: 'task-management-d24b8.firebasestorage.app',
  );
}
